#!/bin/sh

set -e

OPENCILK_VERSION=3
LLVM_VERSION=19
VERSION_TAG=19oc3

# this is taken from libjsoncpp package
# Presence of $AUTOPKGTEST_TMP implies that someone will handle cleanup for us, so we
# can avoid duplicating the effort (signal handling, etc.) here.
if [ -z "$AUTOPKGTEST_TMP" ]
then
	echo "Required envvar AUTOPKGTEST_TMP \"$AUTOPKGTEST_TMP\" is not set" >&2
	exit 1
fi

# Copy the integration repo to the temp dir
cp -Rv integration-test-suite/* "$AUTOPKGTEST_TMP"/
cd "$AUTOPKGTEST_TMP"

mkdir build
cd build
cmake -DLIT=/usr/lib/opencilk-$OPENCILK_VERSION/build/utils/lit/lit.py \
        -DCLANG_BINARY=/usr/bin/clang-$VERSION_TAG \
        -DCLANGXX_BINARY=/usr/bin/clang++-$VERSION_TAG \
        -DCLANG_TIDY_BINARY=/usr/bin/clang-tidy-$VERSION_TAG \
        -DCLANG_FORMAT_BINARY=/usr/bin/clang-format-$VERSION_TAG \
        -DLLD_BINARY=/usr/bin/lld-$VERSION_TAG \
        -DLLDB_BINARY=/usr/bin/lldb-$VERSION_TAG \
        -DLLVMCONFIG_BINARY=/usr/bin/llvm-config-$VERSION_TAG \
        -DOPT_BINARY=/usr/bin/opt-$VERSION_TAG \
        -DSCANBUILD=/usr/bin/scan-build-$VERSION_TAG \
        -DCLANG_TIDY_BINARY=/usr/bin/clang-tidy-$VERSION_TAG \
        -DSCANVIEW=/usr/bin/scan-view-$VERSION_TAG \
        -DLLVMNM=/usr/bin/llvm-nm-$VERSION_TAG \
        -DLLVMPROFDATA=/usr/bin/llvm-profdata-$VERSION_TAG \
        -DENABLE_COMPILER_RT=OFF \
        -DENABLE_LIBCXX=ON \
        -DLLVM_CMAKE_PREFIX_PATH=/usr/lib/opencilk-$OPENCILK_VERSION/lib/cmake/ ../
make check
