#!/bin/sh

set -e

# this is taken from libjsoncpp package
# Presence of $ADTTMP implies that someone will handle cleanup for us, so we
# can avoid duplicating the effort (signal handling, etc.) here.
if [ -z "$ADTTMP" ]
then
	echo "Required envvar ADTTMP \"$ADTTMP\" is not set" >&2
	exit 1
fi

# Copy the integration repo to the temp dir
cp -Rv integration-test-suite/* "$ADTTMP"/
cd "$ADTTMP"

mkdir build
cd build
cmake -DLIT=/usr/lib/llvm-10/build/utils/lit/lit.py \
        -DCLANG_BINARY=/usr/bin/clang-10 \
        -DCLANGXX_BINARY=/usr/bin/clang++-10 \
        -DCLANG_TIDY_BINARY=/usr/bin/clang-tidy-10 \
        -DCLANG_FORMAT_BINARY=/usr/bin/clang-format-10 \
        -DLLD_BINARY=/usr/bin/lld-10 \
        -DLLDB_BINARY=/usr/bin/lldb-10 \
        -DLLVMCONFIG_BINARY=/usr/bin/llvm-config-10 \
        -DOPT_BINARY=/usr/bin/opt-10 \
        -DSCANBUILD=/usr/bin/scan-build-10 \
        -DCLANG_TIDY_BINARY=/usr/bin/clang-tidy-10 \
        -DSCANVIEW=/usr/bin/scan-view-10 \
        -DLLVMNM=/usr/bin/llvm-nm-10 \
        -DLLVMPROFDATA=/usr/bin/llvm-profdata-10 \
        -DENABLE_COMPILER_RT=OFF \
        -DENABLE_LIBCXX=ON \
        -DLLVM_CMAKE_PREFIX_PATH=/usr/lib/llvm-10/lib/cmake/ ../
make check
